general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: true

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: true

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: false

  # Whether to show floating windows as always on top.
  show_floating_on_top: true

  # Amount to move floating windows by (eg. when using `Ctrl+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "false"


gaps:
  # Gap between adjacent windows.
  inner_gap: "8px"

  # Gap between windows and the screen edge.
  outer_gap: "12px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#ffc000"

  inactive:
    enabled: false
    color: "#ff0000"
bar:
  height: "30px"
  position: "top"
  opacity: 1.0
  background: "#1f1f1f"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "16px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
    - type: "window title"
      label: " |  {window_title}"
  components_center:
    - type: "cpu"
      label: " CPU: {percent_usage}%"
      refresh_interval_ms: 1000
    - type: "memory"
      label: " | RAM: {percent_usage}%"
    - type: "network"
      label_no_internet: "NC"
      label_ethernet: " | Eth"
      label_wifi_strength_0: "WiFi: 0%"
      label_wifi_strength_25: "WiFi: 25%"
      label_wifi_strength_50: "WiFi: 50%"
      label_wifi_strength_75: "WiFi: 75%"
      label_wifi_strength_100: "WiFi: 100%"
      refresh_interval_ms: 1000
  components_right:
    - type: "system tray"
    - type: "volume"
      label_low: "  🔊 {volume_level}%"
      label_medium: "  🔊 {volume_level}%"
      label_high: "  🔊 {volume_level}%"
      label_mute: "  🔊 {volume_level}%"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: "  d.MM.yyy | H:mm"

workspaces:
  #         
  - name: "1"
    display_name: "1"
    bind_to_monitor: 1
    keep_alive: true
  - name: "2"
    display_name: "2"
    keep_alive: true
    bind_to_monitor: 1
  - name: "3"
    display_name: "3"
    keep_alive: true
    bind_to_monitor: 1
  - name: "4"
    display_name: "4"
    keep_alive: true
    bind_to_monitor: 1
  - name: "5"
    display_name: "5"
    keep_alive: true
    bind_to_monitor: 1
  - name: "6"
    display_name: "6"
    keep_alive: true
    bind_to_monitor: 2
  - name: "7"
    display_name: "7"
    keep_alive: true
    bind_to_monitor: 2
  - name: "8"
    display_name: "8"
    keep_alive: true
    bind_to_monitor: 2
  - name: "9"
    display_name: "9"
    keep_alive: true
    bind_to_monitor: 3
  - name: "10"
    display_name: "10"
    keep_alive: true
    bind_to_monitor: 3

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+A"]
  - command: "focus right"
    bindings: ["Alt+D"]
  - command: "focus up"
    bindings: ["Alt+W"]
  - command: "focus down"
    bindings: ["Alt+S"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+A"]
  - command: "move right"
    bindings: ["Alt+Shift+D"]
  - command: "move up"
    bindings: ["Alt+Shift+W"]
  - command: "move down"
    bindings: ["Alt+Shift+S"]

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Ctrl+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+F"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Ctrl+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Ctrl+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Ctrl+Shift+R"

  # Launch CMD terminal (Ctrlernatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec pwsh"
    binding: "Ctrl+Enter"
  - command: "exec firefox"
    binding: "Ctrl+B"
  - command: "exec explorer"
    binding: "Ctrl+E" 

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Ctrl+1"
  - command: "focus workspace 2"
    binding: "Ctrl+2"
  - command: "focus workspace 3"
    binding: "Ctrl+3"
  - command: "focus workspace 4"
    binding: "Ctrl+4"
  - command: "focus workspace 5"
    binding: "Ctrl+5"
  - command: "focus workspace 6"
    binding: "Pause+1"
  - command: "focus workspace 7"
    binding: "Pause+2"
  - command: "focus workspace 8"
    binding: "Pause+3"
  - command: "focus workspace 9"
    binding: "Pause+4"
  - command: "focus workspace 10"
    binding: "Pause+5"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Ctrl+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Ctrl+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Ctrl+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Ctrl+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Ctrl+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Pause+Ctrl+1"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Pause+Ctrl+2"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Pause+Ctrl+3"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Pause+Ctrl+4"]
  - commands: ["move to workspace 10", "focus workspace 10"]
    bindings: ["Pause+Ctrl+5"]
